//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.30 at 06:24:06 PM IST 
//


package com.unico.schemas;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mycompany.login.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mycompany.login.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GCDListRequest }
     * 
     */
    public GCDListRequest createGCDListRequest() {
        return new GCDListRequest();
    }

    /**
     * Create an instance of {@link GCDListResponse }
     * 
     */
    public GCDListResponse createGCDListResponse() {
        return new GCDListResponse();
    }

    /**
     * Create an instance of {@link GCDRequest }
     * 
     */
    public GCDRequest createGCDRequest() {
        return new GCDRequest();
    }

    /**
     * Create an instance of {@link GCDResponse }
     * 
     */
    public GCDResponse createGCDResponse() {
        return new GCDResponse();
    }

    /**
     * Create an instance of {@link GCDSumResponse }
     * 
     */
    public GCDSumResponse createGCDSumResponse() {
        return new GCDSumResponse();
    }

    /**
     * Create an instance of {@link GCDSumRequest }
     * 
     */
    public GCDSumRequest createGCDSumRequest() {
        return new GCDSumRequest();
    }

}
